version: "3.9"

services:
  app:
    build: .
    container_name: mangos_app
    ports:
      - "8090:80"
    volumes:
      - ./mini-framework:/var/www
    depends_on:
      - db
    networks:
      - mangos_net
    command: /usr/local/bin/wait-for-db.sh db 3306 -- /usr/sbin/apache2ctl -D FOREGROUND

  db:
    image: mariadb:11
    container_name: mangos_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyutu
      MYSQL_USER: proyutu
      MYSQL_PASSWORD: 12345678
    volumes:
      - db_data:/var/lib/mysql
      - ./proyutu.sql:/docker-entrypoint-initdb.d/proyutu.sql
    networks:
      - mangos_net

networks:
  mangos_net:

volumes:
  db_data:
