version: "3.9"

services:
  app:
    build: .
    container_name: mangos_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - mangos_net

  db:
    image: mariadb:11
    container_name: mangos_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyutu
      MYSQL_USER: proyutu
      MYSQL_PASSWORD: 12345678
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mangos_net

networks:
  mangos_net:

volumes:
  db_data:
